### ISSUE TITLE
Would it be possible to use git stash -u or -a and not bail out at unsaved files?

### ISSUE THREAD

**Issue by jmunson** [maruel/pre-commit-go#15]
So far my biggest frustration with pcg is it makes it so you can not create multiple files and then just commit a few of them, as the untracked files stops pcg from using git stash.

Would it be possible for pcg to use git stash --include-untracked or --all to just stash those files anyways, or am I overlooking some reason that this would be bad?

**Comment by maruel** [comment]
In my personal workflow, I never keep anything untracked. I view an untracked file as a user error. The reason is that this error is very easy to do with Go since the tooling does a glob by default, so you won't notice that you forgot to git add a file until it's really too late.

In practice you can `git add .; git stash; pcg; git stash pop; git reset` but I assume that's not something of interest of you. In that case I'm fine with adding a flag but I feel it's more typing that doing the right thing in the first place.

**Comment by maruel** [comment]
Closing old issues, as recent Go versions made pcg less relevant.
